config/routes.rb
Rails.application.routes.draw do
  devise_scope :athlete do
    get '/athletes/sign_up/:coach_id', :to => 'athletes/registrations#new', as: :new_coach_athlete_registration
  end

  devise_for :athletes, :controllers => { registrations: 'athletes/registrations', passwords: 'athletes/passwords', sessions: 'athletes/sessions'}, :path_names => { sign_up: ''}

  devise_for :coaches, controllers: { registrations: "coaches/registrations", sessions: 'coaches/sessions' }
  root to: "home#index"

  resources :coaches, :only => [:show] do
    resources :athletes
  end

  resources :athletes, :only => [] do
    resources :workouts
  end

  resources :athletes, :only => [] do
    resources :exercises
    get :cancel, to: "exercises#cancel"
  end

  resources :exercises, :only => [] do
    get :hide_history, to: "exercises#hide_history"
  end

  resources :about, :only => [:index]

  post 'coaches/:id/invite', to: 'athletes#invite', as: :invite
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  validates :date, :workout, :presence => true
  belongs_to :athlete

  def self.search(search)
    if search
      where('workout LIKE ?', "%#{search}%")
    else
      self.all
    end
  end

  scope :today, ->(athlete) { where(date: Time.zone.now.beginning_of_day).where(athlete_id: athlete.id) }

  scope :previous, ->(workout_date) {
    where("date < ?", workout_date).order("date DESC").first
  }

  scope :next, ->(workout_date) {
    where("date > ?", workout_date).order("date").first
  }

  scope :date_number, ->(date) {
    where(date: date).length
  }

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :authenticate_coach!, :only => [:create, :destroy]
  include ApplicationHelper
  expose :athlete

  def show
    if invalid_workout_user
      redirect_to root_path
    else
      @workout = Workout.find(params[:id])
      @link_filter = AutoHtml::Link.new(target: '_blank')
      @previous = athlete.workouts.previous(@workout.date)
      @next = athlete.workouts.next(@workout.date)
    end
  end

  def edit
    if invalid_workout_user
      redirect_to root_path
    else
      @workout = Workout.find(params[:id])
      @link_filter = AutoHtml::Link.new(target: '_blank')
      @workouts = athlete.workouts.paginate(:page => params[:page], :per_page => 7).order(date: :desc)
      @previous = athlete.workouts.previous(@workout.date)
      @next = athlete.workouts.next(@workout.date)
      respond_to do |format|
        format.html { athlete_workout_path(athlete, @workout) }
        format.js
      end
    end
  end

  def update
    @workout = Workout.find(params[:id])
    @link_filter = AutoHtml::Link.new(target: '_blank')
    if invalid_workout_user
      redirect_to root_path
    elsif invalid_date(@workout, athlete, update_params[:date])
      flash[:notice] = "You may not add more than one workout for a day. Instead, edit the day's training to include multiple sessions."
      redirect_to athlete_workout_path(athlete, @workout)
    else
      @previous = athlete.workouts.previous(@workout.date)
      @next = athlete.workouts.next(@workout.date)
      if @workout.update(update_params)
        respond_to do |format|
          format.html { athlete_workout_path(athlete, @workout) }
          format.js
        end
      else
        redirect_to athlete_workout_path(athlete, @workout)
      end
    end
  end

  def create
    if current_coach != athlete.coach
      redirect_to new_coach_session_path
    else
      @today_workout = Workout.today(athlete)
      @workouts = athlete.workouts.paginate(:page => params[:page], :per_page => 7).order(date: :desc)
      @workout = athlete.workouts.new
      @link_filter = AutoHtml::Link.new(target: '_blank')
      @new_workout = athlete.workouts.new(workout_params)
      if athlete.workouts.date_number(workout_params[:date]) > 0
        flash[:notice] = "You may not add more than one workout for a day. Instead, edit the day's training to include multiple sessions."
        redirect_to coach_athlete_path(athlete.coach, athlete)
      elsif @new_workout.save
        respond_to do |format|
          format.html { coach_athlete_path(athlete.coach, athlete) }
          format.js
        end
      else
        redirect_to coach_athlete_path(athlete.coach, athlete)
      end
    end
  end

  def destroy
    if current_coach != athlete.coach
      redirect_to new_coach_session_path
    else
      @link_filter = AutoHtml::Link.new(target: '_blank')
      @workout = Workout.find(params[:id])
      @workout.destroy
      redirect_to coach_athlete_path(athlete.coach, athlete)
    end
  end

  private

  def workout_params
    params.require(:workout).permit(:date, :workout, :coach_notes)
  end

  def update_params
    params.require(:workout).permit(:results, :athlete_notes, :date, :workout, :coach_notes)
  end
end

app/views/workouts/_all_workouts.html.erb
<h2>All Workouts</h2>
<% @workouts.each do |workout| %>
  <p><%= link_to workout.try(:date).try(:strftime, ('%a %d %b %Y')), athlete_workout_path(workout.athlete, workout) %></p>
<% end %>
<%= will_paginate @workouts %>

app/views/workouts/_results_form.html.erb
<% if current_athlete && current_athlete == athlete %>
  <div class="coach-registration coach-box" >
    <%= form_for [athlete, @workout], method: "patch", remote: true do |f| %>
    <%= f.label :results %>
    <%= f.text_area :results, :class => 'big-field', :required => true%>
    <%= f.label :athlete_notes %>
    <%= f.text_area :athlete_notes, :class => 'medium-field' %>
    <%= f.submit 'Submit Results', :class => 'btn home-btn' %>
    <% end %>
  </div>
<% end %>

<% if current_coach && current_coach == athlete.coach %>
  <div class="coach-registration coach-box">
    <%= form_for [athlete, @workout], method: "patch", remote: true do |f| %>
      <%= f.label :date %>
      <%= f.date_field :date, :required => true %>
      <%= f.label :workout %>
      <%= f.text_area :workout, :class => 'big-field', :required => true %>
      <%= f.label :coach_notes %>
      <%= f.text_area :coach_notes, :class => 'medium-field' %>
      <%= f.submit 'Update Workout', :class => 'btn home-btn' %>
    <% end %>
  </div>
<% end %>

app/views/workouts/_today_workout.html.erb
<% @today_workout.each do |workout| %>
  <h3><%= link_to 'Today', athlete_workout_path(athlete, workout.id) %></h3>
  <%= simple_format(@link_filter.call(workout.workout)) %>
  <% if workout.coach_notes != '' %>
    <h5>Coach's Notes</h5>
    <%= simple_format(@link_filter.call(workout.coach_notes)) %>
  <% end %>
  <% if workout.results %>
    <h5>Results</h5>
    <%= simple_format(@link_filter.call(@today_workout[0].results)) %>
    <h5>Athlete Notes</h5>
    <%= simple_format(@link_filter.call(@today_workout[0].athlete_notes)) %>
  <% end %>
<% end %>

app/views/workouts/_workout_form.html.erb
<div class="coach-registration coach-box">
  <div class="field">
    <h2>New Workout</h2>
    <%= form_for [athlete, @workout], remote: true do |f| %>
      <%= f.label :date %>
      <%= f.date_field :date, :required => true %>
      <%= f.label :workout %>
      <%= f.text_area :workout, :class => 'big-field', :required => true %>
      <%= f.label :coach_notes %>
      <%= f.text_area :coach_notes, :class => 'medium-field' %>
      <%= f.submit 'Create Workout', :class => 'btn home-btn' %>
    <% end %>
  </div>
</div>

app/views/workouts/_workout_info.html.erb
<div class="workout-nav">
  <% if @previous.is_a?(Workout) %>
    <%= link_to image_tag("prev-icon.png", class: 'prev'), athlete_workout_path(athlete, @previous) %>
  <% end %>
  <% if @next.is_a?(Workout) %>
    <%= link_to image_tag("next-icon.png", class: 'next'), athlete_workout_path(athlete, @next) %>
  <% end %>
  <h4 class="bordered"><%= @workout.try(:date).try(:strftime, ('%a %d %b %Y')) %></h4>
</div>

<p><%= simple_format(@link_filter.call(@workout.workout)) %></p>
<% if @workout.coach_notes != '' %>
  <h5>Coach's Notes</h5>
  <p><%= simple_format(@link_filter.call(@workout.coach_notes)) %></p>
<% end %>
<% if current_coach %>
  <p><%= link_to 'Edit Workout', edit_athlete_workout_path(athlete, @workout), remote: true %></p>
  <p><%= link_to 'Delete Workout', athlete_workout_path(athlete, @workout), :data => {:confirm => "Are you sure you want to delete this workout?", :method => "delete"} %></p>
<% end %>

<div id="workout-results">
  <%= render 'workout_results' %>
</div>

app/views/workouts/_workout_results.html.erb
<% if (@workout.results && current_athlete) || (@workout.results && current_coach) %>
  <h4 class="bordered">Results</h4>
  <%= simple_format(@link_filter.call(@workout.results)) %>
  <h4 class="bordered">Athlete Notes</h4>
  <%= simple_format(@link_filter.call(@workout.athlete_notes)) %>
  <% if current_athlete %>
    <%= link_to 'Edit Results', edit_athlete_workout_path(athlete, @workout), remote: true %>
  <% end %>
<% elsif current_athlete %>
  <%= link_to 'Add Results', edit_athlete_workout_path(athlete, @workout), remote: true %>
<% end %>

app/views/workouts/create.js.erb
$('.workout-form').html("<%= j render 'workouts/workout_form' %>");
$('.today-workout').html("<%= j render 'workouts/today_workout' %>");
$('.all-workouts').html("<%= j render 'workouts/all_workouts' %>");
$('#workout_date').val('');
$('#workout_workout').val('');
$('#workout_coach_notes').val('');

app/views/workouts/edit.js.erb
$('#results-edit-form').html("<%= j render 'results_form' %>");
$('.all-workouts').html("<%= j render 'workouts/all_workouts' %>");

app/views/workouts/show.html.erb
<div class="coach-container">
  <div class="coach-registration coach-box">
    <div id="workout-info">
      <%= render 'workout_info' %>
    </div>
    <h5><%= link_to "Return to Profile", coach_athlete_path(athlete.coach, athlete) %></h5>
  </div>
  <div id="results-edit-form"></div>
</div>

app/views/workouts/update.js.erb
$('#results-edit-form').html("");
$('#workout-results').html("<%= j render 'workout_results' %>");
$('#workout-info').html("<%= j render 'workout_info' %>");