config/routes.rb
Rails.application.routes.draw do
  devise_scope :athlete do
    get '/athletes/sign_up/:coach_id', :to => 'athletes/registrations#new', as: :new_coach_athlete_registration
  end

  devise_for :athletes, :controllers => { registrations: 'athletes/registrations', passwords: 'athletes/passwords', sessions: 'athletes/sessions'}, :path_names => { sign_up: ''}

  devise_for :coaches, controllers: { registrations: "coaches/registrations", sessions: 'coaches/sessions' }
  root to: "home#index"

  resources :coaches, :only => [:show] do
    resources :athletes
  end

  resources :athletes, :only => [] do
    resources :workouts
  end

  resources :athletes, :only => [] do
    resources :exercises
    get :cancel, to: "exercises#cancel"
  end

  resources :exercises, :only => [] do
    get :hide_history, to: "exercises#hide_history"
  end

  resources :about, :only => [:index]

  post 'coaches/:id/invite', to: 'athletes#invite', as: :invite
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/views/home/index.html.erb
<div class="home-container">
  <div class="home-intro">
    <h1>BeTrained</h1>
    <div id="border"></div>
    <h3 class="home-description">Share workouts, feedback, and instruction with your training clients. Give yourself more time to focus on what you do best: coaching.</h3>
    <div class="row home-buttons-large">
      <% if !current_coach && !current_athlete %>
        <div class="col s3">
          <%= button_to "Learn More", about_index_path, :class => 'btn home-btn', :method => :get %>
        </div>
        <div class="col s3">
          <%= button_to "Register as a Coach", new_coach_registration_path, :class => "btn home-btn", :method => :get %>
        </div>
        <div class="col s3">
          <%= button_to "Coach Sign In", new_coach_session_path, :class => "btn home-btn", :method => :get %>
        </div>
        <div class="col s3">
          <%= button_to "Athlete Sign In", new_athlete_session_path, :class => "btn home-btn", :method => :get %>
        </div>
      <% elsif current_coach %>
        <div class="col s3"></div>
        <div class="col s3">
          <%= button_to "Coach Console", coach_path(current_coach), class: 'btn btn-home', :method => :get %></li>
        </div>
        <div class="col s3">
          <%= button_to "Log Out", destroy_coach_session_path, method: :delete, class: 'btn btn-home' %>
        </div>
        <div class="col s3"></div>
      <% elsif current_athlete %>
        <div class="col s3"></div>
        <div class="col s3">
          <%= button_to "My Profile", coach_athlete_path(current_athlete.coach, current_athlete), class: 'btn btn-home', :method => :get %>
        </div>
        <div class="col s3">
          <%= button_to "Log Out", destroy_athlete_session_path, method: :delete, class: 'btn btn-home' %>
        </div>
        <div class="col s3"></div>
      <% end %>

    </div>
    <div class="row home-buttons-small">
      <% if !current_coach && !current_athlete %>
        <%= button_to "Learn More", about_index_path, :class => 'btn home-btn', :method => :get %>
        <%= button_to "Register as a Coach", new_coach_registration_path, :class => "btn home-btn", :method => :get %>
        <%= button_to "Coach Sign In", new_coach_session_path, :class => "btn home-btn", :method => :get %>
        <%= button_to "Athlete Sign In", new_athlete_session_path, :class => "btn home-btn", :method => :get %>
      <% elsif current_coach %>
        <%= button_to "Coach Console", coach_path(current_coach), class: 'btn home-btn', :method => :get %>
        <%= button_to "Log Out", destroy_coach_session_path, method: :delete, class: 'btn home-btn' %>
      <% elsif current_athlete %>
        <%= button_to "My Profile", coach_athlete_path(current_athlete.coach, current_athlete), class: 'btn home-btn', :method => :get %>
        <%= button_to "Log Out", destroy_athlete_session_path, method: :delete, class: 'btn home-btn' %>
      <% end %>
    </div>
  </div>
</div>