config/routes.rb
Rails.application.routes.draw do
  devise_scope :athlete do
    get '/athletes/sign_up/:coach_id', :to => 'athletes/registrations#new', as: :new_coach_athlete_registration
  end

  devise_for :athletes, :controllers => { registrations: 'athletes/registrations', passwords: 'athletes/passwords', sessions: 'athletes/sessions'}, :path_names => { sign_up: ''}

  devise_for :coaches, controllers: { registrations: "coaches/registrations", sessions: 'coaches/sessions' }
  root to: "home#index"

  resources :coaches, :only => [:show] do
    resources :athletes
  end

  resources :athletes, :only => [] do
    resources :workouts
  end

  resources :athletes, :only => [] do
    resources :exercises
    get :cancel, to: "exercises#cancel"
  end

  resources :exercises, :only => [] do
    get :hide_history, to: "exercises#hide_history"
  end

  resources :about, :only => [:index]

  post 'coaches/:id/invite', to: 'athletes#invite', as: :invite
end

app/models/coach.rb
class Coach < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :athletes
  validates :first_name, :last_name, :presence => true
end

app/controllers/coaches/registrations_controller.rb
class Coaches::RegistrationsController < Devise::RegistrationsController
  def create
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end
  protected

  def after_sign_up_path_for(coach)
    coach_path(current_coach)
  end

  def sign_up_params
    params.require(:coach).permit(:email, :password, :password_confirmation, :first_name, :last_name)
  end

  def account_update_params
    params.require(:coach).permit(:email, :password, :password_confirmation, :current_password, :first_name, :last_name)
  end

end

app/controllers/coaches/sessions_controller.rb
class Coaches::SessionsController < Devise::SessionsController
  def new
    if current_athlete
      flash[:notice] = "You will be signed out of your athlete account."
    end
    super
  end

  def create
    if current_athlete
      sign_out current_athlete
    end
    super
  end
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  before_action :authenticate_coach!
  expose :coach

  def show
    if current_coach && current_coach == coach
      @athletes = coach.athletes.confirmed
      @unconfirmed = coach.athletes.unconfirmed
    else
      redirect_to new_coach_session_path
    end
  end
end

app/views/coaches/_clients.html.erb
<div class="coach-registration coach-box">
  <h2>Your Athletes</h2>
  <% @athletes.each do |athlete| %>
  <h5><%= link_to "#{athlete.first_name} #{athlete.last_name}", coach_athlete_path(coach, athlete) %></h5>
  <!--pagination, links-->
  <% end %>
  <% if @unconfirmed.any? %>
  <h2>Unconfirmed</h2>
  <% @unconfirmed.each do |athlete| %>
  <h5>
    <%= athlete.first_name %> <%= athlete.last_name %>
    <%= link_to image_tag("checkmark.png", class: 'confirmation'), coach_athlete_path(coach, athlete, :accept => true), remote: true, :method => :patch %>
    <%= link_to image_tag("red_x.png", class: 'confirmation'), coach_athlete_path(coach, athlete, :ignore => true), remote: true, :method => :patch %>
  </h5>
  <% end %>
  <% end %>
</div>

<div class="coach-registration lower-box">
  <div class="field">
    <h2>Invite</h2>
    <%= form_tag invite_path(coach) do %>
    <%= label_tag :email %>
    <%= email_field_tag :email %>
    <%= submit_tag 'Send Invite', class: 'btn home-btn' %>
    <% end %>
  </div>
</div>

app/views/coaches/show.html.erb
<div class="coach-container">
  <%= render 'clients' %>
</div>