config/routes.rb
Rails.application.routes.draw do
  devise_scope :athlete do
    get '/athletes/sign_up/:coach_id', :to => 'athletes/registrations#new', as: :new_coach_athlete_registration
  end

  devise_for :athletes, :controllers => { registrations: 'athletes/registrations', passwords: 'athletes/passwords', sessions: 'athletes/sessions'}, :path_names => { sign_up: ''}

  devise_for :coaches, controllers: { registrations: "coaches/registrations", sessions: 'coaches/sessions' }
  root to: "home#index"

  resources :coaches, :only => [:show] do
    resources :athletes
  end

  resources :athletes, :only => [] do
    resources :workouts
  end

  resources :athletes, :only => [] do
    resources :exercises
    get :cancel, to: "exercises#cancel"
  end

  resources :exercises, :only => [] do
    get :hide_history, to: "exercises#hide_history"
  end

  resources :about, :only => [:index]

  post 'coaches/:id/invite', to: 'athletes#invite', as: :invite
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  expose :athlete
  expose :exercises, ->{ athlete.exercises.order("updated_at DESC") }
  include ApplicationHelper
  helper_method :sort_column, :sort_direction

  def new
    @exercise = athlete.exercises.new
    respond_to do |format|
      format.js
    end
  end

  def create
    exercise = athlete.exercises.create(exercise_params)
    respond_to do |format|
      format.js
    end
  end

  def edit
    @exercise = Exercise.find(params[:id])
    respond_to do |format|
      format.js { render :new }
    end
  end

  def update
    @exercise = Exercise.find(params[:id])
    @exercise.update(exercise_params)
    respond_to do |format|
      format.js { render :create }
    end
  end

  def show
    @exercise = Exercise.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @exercise = Exercise.find(params[:id])
    @exercise.destroy
    respond_to do |format|
      format.js
    end
  end

  def cancel
    respond_to do |format|
      format.js { render :create }
    end
  end

  def hide_history
    @exercise = Exercise.find(params[:exercise_id])
    respond_to do |format|
      format.js
    end
  end

  private

  def exercise_params
    params.require(:exercise).permit(:name, :record, :date, :unit)
  end

  def sort_column
    Exercise.column_names.include?(params[:sort]) ? params[:sort] : "date"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/views/exercises/_hide_history.html.erb
<%= link_to "Hide", exercise_hide_history_path(@exercise), remote: true, method: :get %>

app/views/exercises/_new_record_link.html.erb
<%= link_to "Add a New Record", new_athlete_exercise_path(athlete), remote: true %>

app/views/exercises/_personal_record_form.html.erb
<div class="field">
  <h3>Add a Personal Record</h3>
  <%= form_for [athlete, @exercise], remote: true do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, required: true %>
    <%= f.label :record %>
    <%= f.number_field :record, required: true %>
    <%= f.label :unit %>
    <%= f.select(:unit, options_for_select(Exercise::UNITS), {required: true}) %>
    <%= f.label :date %>
    <%= f.date_field :date, required: true, :value => Time.now.strftime('%Y-%m-%d')%>
    <%= f.submit "Post Record", class: 'btn home-btn' %>
  <% end %>
</div>
  <%= button_to "Cancel", athlete_cancel_path(athlete), class: "btn home-btn", remote: true, method: :get %>

<!-- add cancel button -->

app/views/exercises/_personal_records_list.html.erb
<table style="width:100%" class="records">
  <tr>
    <th><%= sortable("name", athlete) %></th>
    <th><%= sortable("record", athlete) %></th>
    <th><%= sortable("date", athlete) %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% exercises.each do |exercise| %>
    <tr>
      <td><%= exercise.name %></td>
      <td>
        <%= exercise.fixed_record %>
        <% if exercise.unit != "Seconds" %>
          <%= exercise.unit %>
        <% end %>
      </td>
      <td><%= exercise.pretty_date %></td>
      <td><%= link_to "Update", edit_athlete_exercise_path(athlete, exercise), remote: true %></td>
      <td><%= link_to "Delete", athlete_exercise_path(athlete, exercise), remote: true, method: :delete, data: { confirm: "Are you sure you want to delete this personal record?" } %></td>
      <td id="<%= exercise.id %>_show_link"><%= render "exercises/show_history", athlete: athlete, exercise: exercise %></td>
    </tr>
  <% end %>
</table>

<% exercises.each do |exercise| %>
  <div id="<%= exercise.id %>_history" class="hidden">
    <h4><%= exercise.name %> History</h4>
    <table>
      <tr>
        <th>Record</th>
        <th>Date</th>
      </tr>
      <% exercise.revisions_in_order.each do |revision| %>
        <tr>
          <td>
            <%= revision.fixed_record %>
            <% if revision.unit != "Seconds" %>
              <%= revision.unit %>
            <% end %>
          </td>
          <td><%= revision.pretty_date %></td>
        </tr>
      <% end %>
    </table>
  </div>
<% end %>

app/views/exercises/_show_history.html.erb
<%= link_to "Show History", athlete_exercise_path(athlete, exercise), remote: true %>

app/views/exercises/create.js.erb
$("#personal-records-list").html("<%= j render('personal_records_list') %>");
$("#personal-records-form").html("<%= j render('new_record_link') %>");

app/views/exercises/destroy.js.erb
$("#personal-records-list").html("<%= j render('personal_records_list') %>");

app/views/exercises/hide_history.js.erb
$("#<%= @exercise.id %>_history").hide();
$("#<%= @exercise.id %>_show_link").html("<%= j render 'show_history', exercise: @exercise, athlete: @exercise.athlete %>");

app/views/exercises/new.js.erb
$("#personal-records-form").html("<%= j render('personal_record_form') %>");

app/views/exercises/show.js.erb
$("#<%= @exercise.id %>_history").show();
$("#<%= @exercise.id %>_show_link").html("<%= j render('hide_history') %>");